version: '3.9'

services:

  # traefik:
  #   image: "traefik:v2.9"
  #   container_name: "traefik"
  #   command:
  #     #- "--log.level=DEBUG"
  #     - "--api.insecure=true"
  #     - "--providers.docker=true"
  #     - "--providers.docker.exposedbydefault=false"
  #     - "--entrypoints.web.address=:80"
  #   ports:
  #     - "80:80"
  #     - "8080:8080"
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock:ro"

  docusaurus:
    image: node:19
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.docusaurus.rule=Host(`doc.localhost`)"
      - "traefik.http.routers.docusaurus.entrypoints=web"
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "3003:3000"
      - 8976:8976
    command:
      - /bin/bash
      - -c
      - cd site && npm run start -- --host 0.0.0.0

  # nginx:
  #   image: nginx
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.nginx.rule=Host(`nginx.doc.localhost`)"
  #     - "traefik.http.routers.nginx.entrypoints=web"
  #   volumes:
  #     - ./site/build:/usr/share/nginx/html:ro
  #   ports:
  #   - 80
